### ISSUE TITLE
There was an error in your GraphQL query

### ISSUE THREAD

**Issue by TomaszWaszczyk** [narative/narative.co#162]
I was trying to install the website, I installed and import Contentful easily, but I got: 

>  ERROR #85907  GRAPHQL
> 
> There was an error in your GraphQL query:
> 
> - Unknown field 'allContentfulArticleQuote' on type 'Query'.

Is it possible to run website without Contentful, having only *.mdx files?

**Comment by brotzky** [comment]
No, not for narrative.co site. You must setup contentful. There's an export of our data model from contentful included in this repo if you want to get it setup.

Sorry about that! A bit annoying -- i agree.

**Comment by TomaszWaszczyk** [comment]
But I have imported to my Contentful's space exported data from the repository. I have made it.

**Comment by brotzky** [comment]
So in Contentful you have the articles and data all setup? In that case there shouldn't be any issues. 

It's possible we have old data in there and it's missing the Article Quotes as your error suggests.

**Comment by TomaszWaszczyk** [comment]
Screenshot:

![image](https://user-images.githubusercontent.com/1605705/66510262-f7086680-ead4-11e9-991e-c5e7968241ad.png)

I have imported the exported Contentful data (found second README.md) and made it successfully within around 4minutes. During process of importing there was no any error. All well done, but while running the webapplication I got error.

**Comment by brotzky** [comment]
Ill export the latest model for you when I get a chance. Must be a mismatch from your side -- sorry about that!

**Comment by brotzky** [comment]
I've exported all the new models to `contentful`. Hopefully this should resolve any issues you've had.

**Comment by TomaszWaszczyk** [comment]
Thanks!

**Comment by iColdPlayer** [comment]
Hi,... I have the same issue here... 

```js
 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "allContentfulArticleQuote" on type "Query". Did you mean "allContentfulArticle", "allContentfulPullQuote", "contentfulArticle", "allContentfulAsset", or "allContentfulAuthor"?

GraphQL request:3:5
2 |   query GetArticleQuotes {
3 |     allContentfulArticleQuote {
  |     ^
4 |       edges {

File: src/sections/home/Home.Testimonial.tsx:11:5

failed extract queries from components - 2.899s
```
I have successfully imported the content to contentful. But then getting the same error about the GraphQl Query.

**Comment by brotzky** [comment]
Ah shoot. I'll have to take a look into this. Strange that the quote didn't properly get exported/imported. Sorry about that @iColdPlayer

**Comment by TomaszWaszczyk** [comment]
Free account on Contentful is enough to run the site or is required more spaces from contentful?

**Comment by brotzky** [comment]
We use a free account from Contentful to run the site.

<img width="494" alt="Screen Shot 2020-01-22 at 4 33 54 PM" src="https://user-images.githubusercontent.com/8007686/72946849-01253c80-3d35-11ea-8063-84df13dbee6d.png">

**Comment by TomaszWaszczyk** [comment]
Thanks for the answer, fast answer. If so, why not to use just mdx file instead of Contentful? What is the advantage of Contentful over just mdx file?

**Comment by brotzky** [comment]
Huh weird. I guess I'll have to check the exported JSON is valid and can be imported -- sorry!

We use Contentful mainly for the blog posts. We needed the blog posts and some site content such as job postings and key copy to be editable through UI by someone that doesn't code. A WordPress like interface.

If we started again I'd probably pick Sanity.io over Contentful.

**Comment by obiknows** [comment]
> Thanks for the answer, fast answer. If so, why not to use just mdx file instead of Contentful? What is the advantage of Contentful over just mdx file? Btw. does it work?
> 
> ```
> 
> panta@rhei-box:~/workspaces/narative.co$ yarn contentful:import contentful-export-vnhpjjd2fzcz-master-2019-12-06T17-46-88.json
> yarn run v1.21.1
> $ contentful space import --config contentful.json contentful-export-vnhpjjd2fzcz-master-2019-12-06T17-46-88.json
> 
> /home/panta/.config/yarn/global/node_modules/contentful-cli/lib/cli.js:30
>     if (err) throw err
>              ^
> YError: Invalid JSON config file: contentful.json
>     at Object.runValidation [as _runValidation] (/home/panta/.config/yarn/global/node_modules/contentful-cli/node_modules/yargs/yargs.js:1170:28)
>     at Object.runCommand (/home/panta/.config/yarn/global/node_modules/contentful-cli/node_modules/yargs/lib/command.js:233:36)
>     at Object.parseArgs [as _parseArgs] (/home/panta/.config/yarn/global/node_modules/contentful-cli/node_modules/yargs/yargs.js:1078:30)
>     at Object.runCommand (/home/panta/.config/yarn/global/node_modules/contentful-cli/node_modules/yargs/lib/command.js:200:45)
>     at Object.parseArgs [as _parseArgs] (/home/panta/.config/yarn/global/node_modules/contentful-cli/node_modules/yargs/yargs.js:1078:30)
>     at Object.parse (/home/panta/.config/yarn/global/node_modules/contentful-cli/node_modules/yargs/yargs.js:566:25)
>     at Object.<anonymous> (/home/panta/.config/yarn/global/node_modules/contentful-cli/lib/cli.js:35:4)
>     at Module._compile (internal/modules/cjs/loader.js:776:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
>     at Module.load (internal/modules/cjs/loader.js:643:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
>     at Module.require (internal/modules/cjs/loader.js:683:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at Object.<anonymous> (/home/panta/.config/yarn/global/node_modules/contentful-cli/bin/contentful.js:3:1)
>     at Module._compile (internal/modules/cjs/loader.js:776:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) {
>   name: 'YError',
>   message: 'Invalid JSON config file: contentful.json'
> }
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

@TomaszWaszczyk 
I ran into this error before. I still have the same issue as far as the GraphQL query not working, but importing to Contentful for me works best when running:

```
contentful space import --content-file <contentful-export-file-name.json>
```


I think the `contentful.json` doesn't exist anywhere and the CLI looks for it when the `--config` flag is passed

**Comment by obiknows** [comment]
Yeah I just got my site to load locally after using the most recent export from the root directory: 

```
contentful space import --content-file contentful-export-vnhpjjd2fzcz-master-2019-12-06T17-46-88.json
```

Hope this helps.

**Comment by TomaszWaszczyk** [comment]
Yeah, it seems working. Thanks!

**Comment by brotzky** [comment]
Amazing @obiknows!
Thank you for chiming in and helping everyone out <3.

**Comment by narutogang** [comment]
when I try to import the exported JSON, I encounter this error:
```

The following 35 errors and 9 warnings occurred:

23:31:01 - Rate limit error occurred. Waiting for 1583 ms before retrying...
23:31:03 - Rate limit error occurred. Waiting for 1624 ms before retrying...
23:31:03 - Rate limit error occurred. Waiting for 1687 ms before retrying...
23:31:04 - Rate limit error occurred. Waiting for 1653 ms before retrying...
23:31:05 - Rate limit error occurred. Waiting for 1505 ms before retrying...
23:31:05 - Rate limit error occurred. Waiting for 1501 ms before retrying...
23:31:05 - Rate limit error occurred. Waiting for 1531 ms before retrying...
23:31:05 - Rate limit error occurred. Waiting for 1518 ms before retrying...
23:31:05 - Rate limit error occurred. Waiting for 1696 ms before retrying...
23:35:79 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 10a7a97dd25115898173716fae835134
23:35:14 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 80bb88ccf8b06cbe5c51b33281af24ae
23:35:00 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: d54200c79fc6c012f25e9e6edeab4e32
23:35:22 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 930ffea74d0e78e06a8a948dac976562
23:35:72 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 33e8340762971f4c8812628fda7ecb35
23:35:28 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 08fa98b1023376d2c0ee8423fec9b2a4
23:35:33 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: c7c5579b39874c116cf3205fa8bb0bcb
23:35:89 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 2e3053328b1a8d0e99f170ec126ec608
23:35:41 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 81677e196e59652cc265ef075b5ef12d
23:35:45 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 1120bb8c7318a147ec45d12306ab9876
23:35:46 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 3fcd16c2bc2ffeb2810917818ebb59c2
23:35:96 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 2756d3ec6350c87df4cd57c3ea5c820b
23:35:50 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: febada968ca8ec54ece3d6cc80280991
23:35:18 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 7d93e87c6f84cfb996d241f6fa4cdeb0
23:36:39 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 2198c221b063998e86a704bd7c08bf09
23:36:91 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: ebdea516f1a3e9f92e87158dc4fb70be
23:36:53 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 5861e8eeb3b0067f65044ba90a24481a
23:36:50 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: af45994b6e49492e5f52ec2817aaacb1
23:36:51 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 3b9fe9b64d24ed6ee61cea2393a20ca5
23:36:04 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: d573bede01a43af23b8dfd5acd1c63ee
23:36:62 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: c7e4f80c150dd539de84796486e5c756
23:36:64 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 034987f592ce872040597614cd4f472b
23:36:20 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 23cb42ea195c077491a18145066ec145
23:36:36 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: fbb9638004ff192c76698e6cc64111f5
23:36:70 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: c0efd23f350dba969401fe5da509883b
23:36:27 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: e7989185c2ec69bb4feaac765bfe7fb5
23:36:83 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: aec8eaafe6b22e41f47cd6d4a642a69e
23:36:83 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 6fef9e9e8ae2407529d0e6fb5e551955
23:36:34 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 284098d7923c6b985d94d6d5d08f6f7f
23:36:35 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 0f6493db5f2cfbdcd700a8fd630a7b40
23:36:89 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 2fc33792829153a00e1e3c157303b208
23:36:43 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 239569b1da0cde43dbe102d4a52293b2
23:36:95 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: b49313d0796795280e99229bfe7206fd
23:36:56 - UnresolvedLinks: Status: 422 - Unprocessable Entity - Message: Validation error - Details: notResolvable - Request ID: 95cbccdd95e3fe17e516022402b282df
23:36:56 - Could not publish the following entities: 2HocBdXqWGwdZHyXDSrid3, 4ehfEXNHVpFkD8M7gXTmXr, 2PuqYTzN7eky9GUCgHQS0I, 4mGjwEquRPoNESngLZj6N1, 78DcUOnoS6qQXpiDBSLEOo, 6T4ZASaTbiBoXbmzXYIkyk, 1mJdPoUAy6ha58TfT5cWY9, 7nQrRb9U04IhrzmvcyyPFC, 4t9pp5cztKgeaPanzSm9sT, 6iTp8RssVuMJv6xxoeI5ke, 4hTD2SvnAHVuCamn7xf70H, 5F97yUJcGI43oz9WaShHIn, 7CKC3q2czSh4Vs92RS0qtX, 5zgdcYXjlBxgilALrBDOKc, hfAbrbTGIPUpt1MFln9Du, 2rruAVbTOljZNRY7CRRClZ, 
3NJqcM1Ku7A3NNjXNVnJCS`
```
