### ISSUE TITLE
Publishing source code in Contentful via Gatsby rendering

### ISSUE THREAD

**Issue by TomaszWaszczyk** [narative/narative.co#247]
Do you know how to publish source code via Contentful? I want to try to publish source code like:

```
import { css } from '@emotion/core';
import styled from '@emotion/styled';
import { colors } from './colors';
import { darken, lighten } from 'polished';

export const outer = css`
  position: relative;
  padding: 0 4vw;
`;

// Centered content container blocks
export const inner = css`
  margin: 0 auto;
  max-width: 1040px;
  width: 100%;
`;

export const SiteMain = css`
  z-index: 100;
  flex-grow: 1;
`;
```
But currently displaying is bad, have you implemented the feature?

**Comment by brotzky** [comment]
The way I've worked around this before is by creating a custom Content Model in Contentful named Code or similar. I believe Narative.co has this feature already built in and the Content Model exists. 

You can see an example here: https://www.narative.co/articles/building-your-own-blog-with-gatsby-and-novela

**Comment by TomaszWaszczyk** [comment]
Right! Thanks!

**Comment by TomaszWaszczyk** [comment]
Could you export Contentful json file with that article?

**Comment by TomaszWaszczyk** [comment]
Do you mean the "Code":

![image](https://user-images.githubusercontent.com/1605705/75096632-db908a80-55a1-11ea-9d6f-2e6980f09722.png)

All I got is quite OK, but without nice source code formatting ;/

**Comment by brotzky** [comment]
No, click the "+ Eembed" button there and embed a "Code" content model. 
Paste in your code text into that Code block.

Here's an example from our own post:

<img width="801" alt="Screen Shot 2020-02-23 at 9 09 33 PM" src="https://user-images.githubusercontent.com/8007686/75130008-dc4c1e00-5680-11ea-9fc5-110d9af5ccc2.png">

<img width="1391" alt="Screen Shot 2020-02-23 at 9 10 28 PM" src="https://user-images.githubusercontent.com/8007686/75130030-f128b180-5680-11ea-8601-376a5652ef0e.png">

**Comment by TomaszWaszczyk** [comment]
Thanks!! I understand now how it works.
