### ISSUE TITLE
Contentful

### ISSUE THREAD

**Issue by kuttim** [narative/narative.co#49]
Is there any plans to update documentation of running self instance of the repository with Contentful setup? 
Seems to be havin' some difficulties with contentful, more specifically, the content that resides in the contentful.

**Comment by brotzky** [comment]
Hey @kuttim, good question.

You're right that it requires Contentful to get up and running. Which of these options do you think would be most beneficial?
- Bypasses all Contentful queries if no keys are found
- Create a public Contentful account that mirrors our own and share those keys
- Some other solution?

**Comment by kuttim** [comment]
Hi, how would public contentful account work exactly? I think the second
one would be the best option here.

**Comment by kuttim** [comment]
@brotzky Any update on this, so far?

**Comment by brotzky** [comment]
@kuttim I'll create an export as multiple people have asked for it as well. I'll add it to the repo.

**Comment by Peschonaut** [comment]
Great to see this issue open again. Do you think this solution does the job: https://www.contentful.com/developers/docs/tutorials/general/import-and-export/? Then you could just add a JSON containing the content model and some dummy content to this repo. Happy to help writing a readme for this :)

**Comment by brotzky** [comment]
@Peschonaut yes, exactly what I was thinking.
Would really appreciate the help on the readme.

**Comment by brotzky** [comment]
@Peschonaut I've added an `exports` directory: https://github.com/narative/narative.co/tree/master/exports

This contains a basic `README.md` that can be updated on instructions on how to export/import. If you'd like to create a PR that updates both the main readme and exports readme that would be very much appreciated.

Let me know if there's anything else you need from me or if the export didn't work correctly.

**Comment by kuttim** [comment]
@brotzky Thanks for update.
Mine seems to be getting unprocessable entity on the json file provided at the example, can you try to reproduce this?

**Comment by Peschonaut** [comment]
Hey @kuttim, the issue seems to be that there are some dead-end references. Have a look at this [PR of mine](https://github.com/narative/narative.co/pull/70). I am not sure if removing the dead-ends is a safe thing to do. However, at least this branch builds properly after importing :) Huge thanks @brotzky!

**Comment by brotzky** [comment]
Awesome, thanks @Peschonaut and enjoy :)

I'll update the main README.md as well with instructions on how to get started.
